# image: docker:stable

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  
cache:
  paths:
  - node_modules/

stages:
  - 📦 build
  - ✅ review
  - 🚀 production
  - 📄 cleanup
  
 .deploy_template: &template
    - echo "Deploy to localhost:${PORT}"
    - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_BUILD_REF
    - docker stop reviewapp-demo-$CI_COMMIT_REF_NAME || true
    - docker rm reviewapp-demo-$CI_COMMIT_REF_NAME || true
    - docker run -p 127.0.0.1:$PORT:8080/tcp -d --name reviewapp-demo-$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_BUILD_REF

build:
  stage: 📦 build
  script:
    - echo "Building the app"
    - docker build -t tanuki.app .
    - docker tag tanuki.app:latest $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_BUILD_REF
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_BUILD_REF
  tags:
    - shell

deploy_review:
  stage: ✅ review
  variables:
    GIT_STRATEGY: none
    PORT: 90
  script:
    <<: *template
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://127.0.0.1:$PORT
    on_stop: stop_review
  only:
  - branches
  except:
  - master
  tags:
    - shell
    

deploy_prod:
  stage: 🚀 production
  variables:
    GIT_STRATEGY: none
    PORT: 91
  script:
    <<: *template
  when: manual
  environment:
    name: production
    url: http://127.0.0.1:$PORT
  only:
  - master
  tags:
    - shell

undeploy_prod:
  stage: 📄 cleanup
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review app from dev.loc"
    - docker stop reviewapp-demo-$CI_COMMIT_REF_NAME || true
    - docker rm reviewapp-demo-$CI_COMMIT_REF_NAME || true
  when: manual
  only:
  - master
  environment:
    name: production
    action: stop
  tags:
    - shell

stop_review:
  stage: 📄 cleanup
  variables:
    GIT_STRATEGY: none
  when: manual
  only:
  - branches
  except:
  - master
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  tags:
    - shell
  script:
    - echo "Remove images from runner"
    - docker rmi tanuki.app || true
    - docker rmi registry.gitlab.com/mark.cesario/demos/docker-review-app/master || true
    - echo "Remove images from GitLab registry"
    - docker rmi $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_BUILD_REF || true
